version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data/
  backend:
    image: linkoffee/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static/
      - media:/app/media/
    depends_on:
      - db
  frontend:
    image: linkoffee/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static/
      - docs:/app/docs/
  nginx:
    image: linkoffee/foodgram_gateway
    env_file: .env
    ports:
      - "8000:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/staticfiles/
      - media:/app/media/
    depends_on:
      - db
      - backend
      - frontend
